services:
  shinyproxy:
    image: openanalytics/shinyproxy:3.2.2
    container_name: shinyproxy
    restart: unless-stopped
    volumes:
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml:ro
      - ./shinyproxy/users.yml:/opt/shinyproxy/users.yml:ro
      - ./shinyproxy/templates/:/opt/shinyproxy/templates/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    group_add:
      - ${DOCKER_GID}
    ports:
      - 8080:8080
      # - 9090:9090
    networks:
      - shinyproxy-nw
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # ports:
    #   - 7070:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - shinyproxy-nw
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - shinyproxy-nw

networks:
  shinyproxy-nw:
    name: shinyproxy-nw
    external: true

volumes:
  prom_data: